apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    nodePort: 32018
  selector:
    app: hello
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - env:
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
          valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: kingbike/spring-hello:latest
        imagePullPolicy: Always 
        name: hello
        ports:
          - name: http
            containerPort: 8080
          - name: actuator
            containerPort: 8081
        #resources:
          #limits:
          #  cpu: 500m
          #  memory: 256Mi
          #requests:
          #  cpu: 500m
          #  memory: 256Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: actuator
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: actuator
